$vaultPath = "D:\Obsidian\Main\20 - Permanent Notes"
$files = @(
    "I let my local LLM organize my chaotic Obsidian vault and it and it nailed it.md",
    "IGoogle Theme Maker.md",
    "Imaginary Foundation.md",
    "Instapaper.md",
    "Introduction to the.md",
    "Is it eczema or psoriasis.md",
    "Israel bans fluoridated water.md",
    "Jacqueline Depaul on TikTok.md",
    "Jerry Talbot obituary Link.md",
    "Journaley - A Simple.md",
    "Judaism.md",
    "Key Data Perspective.md",
    "Kindle 3 Tips and Tricks.md",
    "Kindle 4 PC Shortcut.md",
    "LG--- dishwasher.md",
    "LiveCode - The Future.md",
    "LNS JUST PIE CRUST.md",
    "Lee Etta Stanard.md",
    "MAKE Blog QRS halts.md",
    "Making Drums.md",
    "Mapping the Uncharted Terr.md",
    "Marshall Effron JUST PIE CRUST.md",
    "Mastering Git Course.md",
    "Matthew Talbott.md",
    "Micro-Meteorite Hunting.md",
    "Microsoft Sculpt Ergonomic Desktop.md",
    "Mix Magazine.md",
    "Model Behavior Scale M.md",
    "Mr. Money Mustache.md",
    "My Obsidian And Gemini CLI Workflow.md",
    "NLP Strategies - Spelli.md",
    "NRICH - National Resour.md",
    "Nagios NRPE - Compili.md",
    "National Semiconductor.md",
    "Naw Ruz.md",
    "Ninite.md",
    "ORDER BY Clause (Transa.md",
    "Obsidian Frontmatter Tag Fixer.md",
    "Old Man and the Sea Intro.md",
    "Oracle.md",
    "Order Postcards - the.md",
    "Parrot Zick headphones.md",
    "Pecan Crust.md",
    "Pepper Ridge Sandwiches.md",
    "Perl 5 Regex Cheat sheet.md",
    "PersonalWeb - DFW-TALBOT.md",
    "PersonalWeb - Edna Mae Fillingim H.md",
    "PersonalWeb - Henry Charles Bubba.md",
    "PersonalWeb - Loving poster.md",
    "PersonalWeb - MAGAbert.md",
    "PersonalWeb - PT.md",
    "PersonalWeb - Screen clipping ta-7.md",
    "Pinkish background.md",
    "Playing a Musical Saw.md",
    "Pluto is a Planet.md",
    "PrintFriendly.md",
    "QR-Code Generator.md",
    "Quick list of every Windows 10 keyboard shortcut.md",
    "ROOTS Technology.md",
    "Reba Joyce Fillingim.md",
    "Recorder Fingering Charts.md",
    "Refrigerator Dills.md",
    "Request for military.md",
    "Rick Steves Cruiseship Tips.md",
    "S100 Computers - Build your own Z80 Computer.md",
    "SCORM - SCORM Explai.md",
    "Samsung Galaxy Tab S Pro.md",
    "Science.md",
    "Scientists discover virus.md",
    "Screen clipping t-12.md",
    "Screen clipping ta-1.md",
    "Screen clipping ta-1_2.md",
    "Screen clipping ta-4.md",
    "Screen clipping ta-5.md",
    "Screen clipping ta-6.md",
    "Screen clipping take_3.md",
    "Set Up Windows Home Se.md",
    "Shopping List.md",
    "SourceForge Apex - Oracles Application Express.md",
    "Spiced Pumpkin Oat Muffins.md",
    "Sugar Free Apple Pie.md",
    "Summit At Sea.md",
    "Switched On Bach.md",
    "The Last Lecture.md",
    "The Vinyl Anachronist.md",
    "The boy who harnessed the wind.md",
    "Tom Bihn.md",
    "Transactions Screen (WCWBF).md",
    "US path to world cup victory.md",
    "UHJ 2025-12-31 To The Conference of the Continental Boards of Counsellors - AI Summary.md",
    "UHJ 2025-12-31 To the Conference of the Continental Boards of Counsellors - Full Message.md",
    "Unswindle Kindle de-.md",
    "Using AND and OR ope.md",
    "VMware KB Installing.md",
    "Vera Irene Talbot.md",
    "Visual Studio 2022 Professional License Key.md",
    "WCWBF Transactions Screen.md",
    "Welcome to AltairKit.md",
    "Welcome to Writage.md",
    "Where Are Your Keys.md",
    "Which Veggie Burgers are Really the Healthiest.md",
    "Whole Earth Catalog.md",
    "Why humans have allergies.md",
    "Why is Google Books fair use.md",
    "William Henry White.md",
    "William Kamkwamba.md",
    "Wind Chimes Maker.md",
    "windows - vbscript o.md",
    "Windows and Linux Nagios LDAP.md",
    "Wood glue deep cleaning vinyl records.md",
    "WorkRave.md",
    "xkcd Is It Worth the Time.md"
)
$missing = @()
foreach ($f in $files) {
    $path = Join-Path $vaultPath $f
    if (-not (Test-Path $path)) { $missing += $f }
}
Write-Host "Missing files ($($missing.Count)):"
$missing | ForEach-Object { Write-Host "  $_" }
