# write_ps.py - writes find_people_names.ps1
ps = []
a = ps.append
a('param()')
a('$vaultRoot  = "C:\Users\awt\Sync\Obsidian"')
a('$outputFile = "C:\Users\awt\people_name_results.txt"')
a('$excludeFolders = @("15 - People","00 - Home Dashboard","00 - Journal","Templates")')
a('$nonNameWords = @(')
a('    "The","How","What","This","That","My","In","For","To","A","An","Of",')
a('    "And","Or","Is","Are","Was","Were","With","From","New","Old","All",')
a('    "About","Your","Our","Their","Its","It","We","You","He","She","They",')
a('    "Not","But","So","If","On","At","By","As","Up","Do","Go","See","Get",')
a('    "Can","May","Will","Has","Have","Had","Been","Be","Make","Take","Come",')
a('    "Know","Use","Find","Give","Tell","Keep","Let","Put","Set","Run","Try",')
a('    "Ask","Say","Show","Play","Move","Live","Work","Look","Turn","Start",')
a('    "Part","Some","More","Most","One","Two","Three","Four","Five","Six",')
a('    "Black","White","Green","Red","Blue","Yellow","Brown","Dark","Light",')
a('    "Big","Small","High","Low","Long","Short","Good","Bad","Best","First",')
a('    "Last","Next","Other","Same","Only","Just","Also","Even","Still","Well",')
a('    "Now","Then","Here","There","When","Where","Why","Who","Which","While",')
a('    "After","Before","During","Over","Under","Between","Through","Without",')
a('    "North","South","East","West","American","United","National","Global",')
a('    "World","Life","Time","Year","Day","Week","Month","Home","House","School",')
a('    "Book","Page","Note","List","File","Data","Case","Type","Way","Place",')
a('    "People","Person","Man","Woman","Men","Women","Child","Children","Family",')
a('    "Group","Team","Club","Society","Community","Company","Food","Water","Air",')
a('    "Earth","Fire","Mind","Body","Soul","Heart","Hand","Eye","Face","Head",')
a('    "Point","Level","Side","Area","Field","Line","Word","Name","Number",')
a('    "Power","Force","Energy","System","Process","State","Issue","Topic",')
a('    "Summary","Index","Master","Main","MOC","Hub","Dashboard","Overview",')
a('    "Report","Review","Study","Research","Analysis","Guide","Manual",')
a('    "Simple","Easy","Hard","Fast","Slow","Early","Late","Free","Full",')
a('    "Open","Close","Right","Wrong","True","False","Real","Actual",')
a('    "General","Special","Common","Local","Public","Private","Personal",')
a('    "Annual","Daily","Weekly","Monthly","Modern","Ancient","Classic",')
a('    "Basic","Advanced","Central","Primary","Secondary","Final","Total",')
a('    "Great","Little","Much","Many","Few","Both","Each","Every","Any",')
a('    "Always","Never","Often","Sometimes","Usually","Recently","Currently",')
a('    "Already","Again","Back","Down","Out","Off","Far","Near","Away",')
a('    "Together","Apart","Inside","Outside","Above","Below","Across","Along",')
a('    "Toward","Against","Beyond","Within","Among","Around","Behind","Beside",')
a('    "Holy","Sacred","Divine","Lord","God","Allah","Buddha",')
a('    "Than","Such","Less","Very","Really","Quite","Rather","Mostly","Truly",')
a('    "These","Those","Them","Him","Her","Whose","Whom",')
a('    "Neither","Either","Nor","Yet","Once","Twice","Almost","Enough",')
a('    "Second","Third","Based","Introduction","Chapter","Section","Appendix",')
a('    "Volume","Edition","Reading","Writing","Speaking","Thinking","Learning",')
a('    "Teaching","Making","Building","Creating","Finding","Using","Getting","Taking"')
a(')')
a('$nonNameSet = @{}')
a('foreach ($w in $nonNameWords) { $nonNameSet[$w] = $true }')
a('function Test-LooksLikeName {')
a('    param([string]$candidate)')
a('    $candidate = $candidate.Trim()')
a('    if ($candidate -match "\d") { return $false }')
a('    $words = $candidate -split "\s+"')
a('    if ($words.Count -lt 2 -or $words.Count -gt 5) { return $false }')
a('    foreach ($word in $words) {')
a('        if ($word -notmatch "^[A-Z]") { return $false }')
a('        if ($word.Length -lt 2) { return $false }')
a('        if ($nonNameSet.ContainsKey($word)) { return $false }')
a('    }')
a('    return $true')
a('}')
a('function Clean-AuthorValue {')
a('    param([string]$raw)')
a('    $c = $raw -replace \'^[\s\-""\'\'']+\'', \'\'')
a('    $c = $c -replace \'[\s""\'\'']+$\', \'\'')
a('    return $c.Trim()')
a('}')
